### ISSUE TITLE
希望添加允许清空搜索输入框的按钮

### ISSUE THREAD

**Issue by nshusr** [Krryxa/krry-transfer#10]
希望添加允许清空搜索输入框的按钮

**Comment by Krryxa** [comment]
提供了清空搜索输入框的钩子：clearQueryInp ，参数 'left' / 'right'

可以根据需要，绑定自定义按钮的点击事件执行这个钩子方法；

**Comment by nshusr** [comment]
![image](https://user-images.githubusercontent.com/45023042/102607500-5cd59100-4163-11eb-81ac-ad1b5ef9ae97.png)
这个地方能加个按钮么，或者给个插槽

**Comment by Krryxa** [comment]
明白了，晚上更新一波

**Comment by nshusr** [comment]
谢谢大佬

**Comment by Krryxa** [comment]
已更新，请将组件更新至 1.6.9 版本。设置 showClearBtn 属性为 true
