### ISSUE TITLE
手动调用getPageData方法，组件数据未更新

### ISSUE THREAD

**Issue by CelesteCC** [Krryxa/krry-transfer#11]

**Comment by Krryxa** [comment]
getPageData 相应的钩子方法是 getData：参数pageIndex
如果需要手动获取分页数据，请用 this.$refs.xxx.getData(pageIndex)

**Comment by CelesteCC** [comment]
async getPageData(pageIndex, pageSize) {
      debugger;
      console.log(pageIndex, pageSize);
      let that = this;
      this.entListParams.pageNumber = pageIndex;

      let params = {
        pageNumber: this.entListParams.pageNumber,
        pageSize: this.entListParams.pageSize,
        industry: this.entListParams.selectedIndustry,
        entName: this.entListParams.entName,
      };
      let res = await danEntListger(params);
      if (res.code === 10000) {
        let arr = [];
        // that.companyList = res.content.contentList
        if (res.content.contentList.length > 0) {
          for (let i = 0; i < res.content.contentList.length; i++) {
            arr.push({
              id: res.content.contentList[i].entId,
              label: res.content.contentList[i].entName,
            });
          }
        }
        // that.companyList = data;
        that.entListParams.data = arr || [];
        return that.entListParams.data;
        // that.entListParams.total = res.content.total;
      } else {
        this.$message.error(res.message);
      }

    },

return 了一个空数组但是dom没有更新

**Comment by Krryxa** [comment]
有报错吗，我这边测试并没发现这个问题

**Comment by CelesteCC** [comment]
没有报错，就是在select @change方法里面调用this.getPageData(1, this.entListParams.pageSize);这个方法，接口返回的数据为空

**Comment by Krryxa** [comment]
不能这么调用。getPageData 是组件的绑定属性
你的意思是想在 select @change方法里 手动调用获取分页数据的方法是吧？我提供了一个钩子，this.$refs.xxx.getData(pageIndex) 这样来用

**Comment by CelesteCC** [comment]
感谢感谢，已经好了！你真棒

**Comment by Krryxa** [comment]
OK，不客气~
