### ISSUE TITLE
showClearBtn设置为true以后怎么没有出现清空按钮

### ISSUE THREAD

**Issue by CelesteCC** [Krryxa/krry-transfer#13]
<kr-paging
              ref="paging"
              filterable
              :pageTexts="['上一页', '下一页']"
              :boxTitle="['企业列表', '已选中']"
              :dataList="companyList"
              :selectedData="formAttr.enterprise"
              :pageSize="comPagesize"
              :async="true"
              :getPageData="getPageData"
              :getSearchData="getSearchData"
              @onChange="onChange"
              :showClearBtn="true"
            ></kr-paging>
输入框清空后点击回车，keyword依旧是上一次输入的值

**Comment by Krryxa** [comment]
鼠标hover输入框会出现清空按钮，至于你说的“输入框清空后点击回车，keyword依旧是上一次输入的值”，我这并没有出现这种情况呢

**Comment by CelesteCC** [comment]
鼠标hover没有出现清空按钮

**Comment by Krryxa** [comment]
> 鼠标hover没有出现清空按钮

输入框有值的时候hover才会出现，
![image](https://user-images.githubusercontent.com/37185773/112148036-5c440f00-8c18-11eb-81ac-97be1a9f8a08.png)
