### ISSUE TITLE
数据如果在组件mounted时加载完成会导致渲染失败

### ISSUE THREAD

**Issue by yangjiegang** [Krryxa/krry-transfer#15]
dataObj属性绑定的数据只能在组件created时加载完成，如果在mounted时获取并载入数据会导致显示空白。如果这不是BUG建议作者在文档里给予提醒。

**Comment by Krryxa** [comment]
嗯嗯，感谢提醒；你说的是kr-cascader 这个组件，这个组件用的人很少所以很少优化。kr-paging 经常优化所以没有这个问题。
以后有空修一下
