### ISSUE TITLE
getPageData采用后台返回时无法刷新列表

### ISSUE THREAD

**Issue by p0mp0k0** [Krryxa/krry-transfer#5]
getPageData(pageIndex, pageSize) {
      var list = [];
      list(pageIndex, pageSize).then(response => {
        for(var i=0;i<response.rows.length;i++){
          var item = {id:response.rows[i].id,label:response.rows[i].label}
          list.push(item);
        }
        console.log(list);
      });
    return list;
    },

后台调用确认获取到数据，但左侧的列表无法刷新数据

打印日志发现，返回的数据并没有被vue渲染，所以无法更新列表，不知道是为什么

**Comment by p0mp0k0** [comment]
getPageData(pageIndex, pageSize) {
      return new Promise((resolve,reject) => {
        let resData = [];
        list(pageIndex,pageSize).then(response => {
          for(var i=0;i<response.rows.length;i++){
            resData.push({id:response.rows[i].id,label:response.rows[i].serialNo});
          }
          console.log(resData);
        });
        resolve(resData);
      });
}
左侧列表仍然显示无数据，还是不能渲染

**Comment by Krryxa** [comment]
你的 list 方法应该是异步请求吧，为什么把 resolve 放在外面，此时的 resData = []

**Comment by p0mp0k0** [comment]
放在里面也是一样的结果

**Comment by Krryxa** [comment]
可以不返回promise，直接返回对应的数组就行。
你第一个方法，没有用 await ，执行到return的时候是空数组
第二个方法，还是空数组，你可以打印一下的

`// 异步获取分页数据 待选区点击上一页/下一页执行
  async getPageData(pageIndex, pageSize) {
    // 掉接口请求数据
    const resData = await getData({pageIndex: pageIndex, pageSize: pageSize})
    // 将 resData 的数据结构处理成如 dataList、selectedData 一样
    return resData
  }`

**Comment by Krryxa** [comment]
可以不返回promise，直接返回对应的数组就行。
你第一个方法，没有用 await ，执行到return的时候是空数组
第二个方法，还是空数组，你可以打印一下的

参考一下：
// 异步获取分页数据 待选区点击上一页/下一页执行
  async getPageData(pageIndex, pageSize) {
    // 掉接口请求数据
    const resData = await getData({pageIndex: pageIndex, pageSize: pageSize})
    // 将 resData 的数据结构处理成如 dataList、selectedData 一样
    return resData
  }

**Comment by Krryxa** [comment]
可以不返回promise，直接返回对应的数组就行。当初写文档的时候不够严谨，抱歉

参考一下：
// 异步获取分页数据 待选区点击上一页/下一页执行
async getPageData(pageIndex, pageSize) {
// 掉接口请求数据
const resData = await getData({pageIndex: pageIndex, pageSize: pageSize})
// 将 resData 的数据结构处理成如 dataList、selectedData 一样
return resData
}

**Comment by p0mp0k0** [comment]
> 可以不返回promise，直接返回对应的数组就行。当初写文档的时候不够严谨，抱歉
> 
> 参考一下：
> // 异步获取分页数据 待选区点击上一页/下一页执行
> async getPageData(pageIndex, pageSize) {
> // 掉接口请求数据
> const resData = await getData({pageIndex: pageIndex, pageSize: pageSize})
> // 将 resData 的数据结构处理成如 dataList、selectedData 一样
> return resData
> }

采用getPageData这种左侧从后台获取数据的方式，从右边选择数据transfer到左侧的时候，这一条数据并不会添加到左侧列表中。是操作时要直接对应

**Comment by Krryxa** [comment]
每次分页从后台获取的数据，是源数据，左侧是根据右侧已选的数据进行过滤后展示。
同理，从右侧transfer到左侧时，左侧的当前分页的源数据中若 包含这条数据，才会展示这条数据

**Comment by p0mp0k0** [comment]
> 每次分页从后台获取的数据，是源数据，左侧是根据右侧已选的数据进行过滤后展示。
> 同理，从右侧transfer到左侧时，左侧的当前分页的源数据中若 包含这条数据，才会展示这条数据

明白了，我之前搞错了，我以为左右是分开的数据源，好的，我去改一下，谢谢了

**Comment by Krryxa** [comment]
> > 每次分页从后台获取的数据，是源数据，左侧是根据右侧已选的数据进行过滤后展示。
> > 同理，从右侧transfer到左侧时，左侧的当前分页的源数据中若 包含这条数据，才会展示这条数据
> 
> 明白了，我之前搞错了，我以为左右是分开的数据源。
> 好的，我去改一下，谢谢了。
> 再多问一句，右侧数据加载后，左侧是会自动过滤掉吗？

没错
