### ISSUE TITLE
clearQueryInp清除左侧的查询条件后，左侧的数据并不会刷新

### ISSUE THREAD

**Issue by p0mp0k0** [Krryxa/krry-transfer#6]
clearQueryInp清除左侧的查询条件后，左侧的数据并不会刷新，既不会触犯getSearchData，也不会触发getPageData。
my-transfer示例也是如此。

**Comment by Krryxa** [comment]
谢谢提醒，已修复。请更新至 1.6.2 版本

**Comment by Krryxa** [comment]
> clearQueryInp清除左侧的查询条件后，左侧的数据并不会刷新，既不会触犯getSearchData，也不会触发getPageData。
> my-transfer示例也是如此。

谢谢提醒，已修复。请更新至 1.6.2 版本
